version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:15.0.1-browsers
  
    working_directory: ~/repo
steps:
      
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      
      - run: yarn install
   
      - save_cache:
        paths:
          - node_modules
          - ~/.npm 
          - ~/.cache
        key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: yarn lint
      - run: yarn test
